"""empty message

Revision ID: 2d5cca8a3afa
Revises: 2c3009d1dc19
Create Date: 2022-11-03 16:51:39.161677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d5cca8a3afa'
down_revision = '2c3009d1dc19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('playerid', sa.String(length=9), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AwardsPlayers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playerId', sa.String(length=9), nullable=True),
    sa.Column('awardId', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['playerId'], ['people.playerId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('playerID', table_name='awardsplayers')
    op.drop_table('awardsplayers')
    op.drop_table('collegeplaying')
    op.drop_index('divID', table_name='divisions')
    op.drop_table('divisions')
    op.drop_index('playerID', table_name='fieldingpost')
    op.drop_table('fieldingpost')
    op.drop_index('playerID', table_name='managershalf')
    op.drop_table('managershalf')
    op.drop_index('playerID', table_name='awardssharemanagers')
    op.drop_table('awardssharemanagers')
    op.drop_index('playerID', table_name='fieldingofsplit')
    op.drop_table('fieldingofsplit')
    op.drop_index('yearID', table_name='managers')
    op.drop_table('managers')
    op.drop_index('yearID', table_name='teams')
    op.drop_table('teams')
    op.drop_index('yearID', table_name='salaries')
    op.drop_table('salaries')
    op.drop_index('playerID', table_name='awardsshareplayers')
    op.drop_table('awardsshareplayers')
    op.drop_index('yearID', table_name='seriespost')
    op.drop_table('seriespost')
    op.drop_table('parks')
    op.drop_index('yearID', table_name='battingpost')
    op.drop_table('battingpost')
    op.drop_index('playerID', table_name='pitchingpost')
    op.drop_table('pitchingpost')
    op.drop_index('analysisID', table_name='analysis')
    op.drop_table('analysis')
    op.drop_table('homegames')
    op.drop_index('playerID', table_name='halloffame')
    op.drop_table('halloffame')
    op.drop_index('playerID', table_name='fielding')
    op.drop_table('fielding')
    op.drop_table('leagues')
    op.drop_index('playerID', table_name='pitching')
    op.drop_table('pitching')
    op.drop_index('playerID', table_name='awardsmanagers')
    op.drop_table('awardsmanagers')
    op.drop_table('battingarchives')
    op.drop_index('playerID', table_name='fieldingof')
    op.drop_table('fieldingof')
    op.drop_table('teamsfranchises')
    op.drop_index('playerID', table_name='allstarfull')
    op.drop_table('allstarfull')
    op.drop_index('yearID', table_name='appearances')
    op.drop_table('appearances')
    op.drop_table('schools')
    op.drop_index('yearID', table_name='teamshalf')
    op.drop_table('teamshalf')
    op.drop_index('playerIdIndex', table_name='pitchinganalytics')
    op.drop_table('pitchinganalytics')
    op.add_column('batting', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('batting', sa.Column('playerId', sa.String(length=9), nullable=True))
    op.add_column('batting', sa.Column('yearId', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('teamId', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('lgId', sa.String(length=2), nullable=True))
    op.add_column('batting', sa.Column('g', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('g_batting', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('ab', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('r', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('h', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('hr', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('rbi', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('sb', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('cs', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('bb', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('so', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('ibb', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('hbp', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('sh', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('sf', sa.Integer(), nullable=True))
    op.add_column('batting', sa.Column('gidp', sa.Integer(), nullable=True))
    op.alter_column('batting', 'stint',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=True)
    op.drop_index('playerID', table_name='batting')
    op.drop_constraint('batting_ibfk_2', 'batting', type_='foreignkey')
    op.drop_constraint('batting_ibfk_1', 'batting', type_='foreignkey')
    op.drop_constraint('batting_ibfk_3', 'batting', type_='foreignkey')
    op.create_foreign_key(None, 'batting', 'people', ['playerId'], ['playerId'])
    op.drop_column('batting', 'yearID')
    op.drop_column('batting', 'CS')
    op.drop_column('batting', 'ID')
    op.drop_column('batting', 'H')
    op.drop_column('batting', 'lgID')
    op.drop_column('batting', 'teamID')
    op.drop_column('batting', 'BB')
    op.drop_column('batting', 'GIDP')
    op.drop_column('batting', 'G')
    op.drop_column('batting', 'RBI')
    op.drop_column('batting', 'SO')
    op.drop_column('batting', 'IBB')
    op.drop_column('batting', 'G_batting')
    op.drop_column('batting', 'AB')
    op.drop_column('batting', 'SF')
    op.drop_column('batting', 'playerID')
    op.drop_column('batting', 'HBP')
    op.drop_column('batting', 'SB')
    op.drop_column('batting', 'R')
    op.drop_column('batting', 'SH')
    op.drop_column('batting', 'HR')
    op.add_column('people', sa.Column('playerId', sa.String(length=9), nullable=False))
    op.drop_column('people', 'playerID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False))
    op.drop_column('people', 'playerId')
    op.add_column('batting', sa.Column('HR', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('SH', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('R', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('SB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('HBP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False))
    op.add_column('batting', sa.Column('SF', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('AB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('G_batting', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('IBB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('SO', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('RBI', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('G', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('GIDP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('BB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('teamID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True))
    op.add_column('batting', sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True))
    op.add_column('batting', sa.Column('H', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('batting', sa.Column('CS', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.add_column('batting', sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'batting', type_='foreignkey')
    op.create_foreign_key('batting_ibfk_3', 'batting', 'people', ['playerID'], ['playerID'])
    op.create_foreign_key('batting_ibfk_1', 'batting', 'leagues', ['lgID'], ['lgID'])
    op.create_foreign_key('batting_ibfk_2', 'batting', 'teams', ['team_ID'], ['ID'])
    op.create_index('playerID', 'batting', ['playerID', 'yearID', 'stint'], unique=False)
    op.alter_column('batting', 'stint',
               existing_type=mysql.SMALLINT(display_width=6),
               nullable=False)
    op.drop_column('batting', 'gidp')
    op.drop_column('batting', 'sf')
    op.drop_column('batting', 'sh')
    op.drop_column('batting', 'hbp')
    op.drop_column('batting', 'ibb')
    op.drop_column('batting', 'so')
    op.drop_column('batting', 'bb')
    op.drop_column('batting', 'cs')
    op.drop_column('batting', 'sb')
    op.drop_column('batting', 'rbi')
    op.drop_column('batting', 'hr')
    op.drop_column('batting', 'h')
    op.drop_column('batting', 'r')
    op.drop_column('batting', 'ab')
    op.drop_column('batting', 'g_batting')
    op.drop_column('batting', 'g')
    op.drop_column('batting', 'lgId')
    op.drop_column('batting', 'teamId')
    op.drop_column('batting', 'yearId')
    op.drop_column('batting', 'playerId')
    op.drop_column('batting', 'id')
    op.create_table('pitchinganalytics',
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('stint', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('teamid', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('WHIP', mysql.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('analysis_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='pitchinganalytics_ibfk_1'),
    sa.PrimaryKeyConstraint('analysis_ID')
    )
    op.create_index('playerIdIndex', 'pitchinganalytics', ['playerID'], unique=False)
    op.create_table('teamshalf',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=False),
    sa.Column('teamID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=False),
    sa.Column('team_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Half', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=False),
    sa.Column('divID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('div_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('DivWin', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('teamRank', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('W', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('L', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['div_ID'], ['divisions.ID'], name='teamshalf_ibfk_2'),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='teamshalf_ibfk_1'),
    sa.ForeignKeyConstraint(['team_ID'], ['teams.ID'], name='teamshalf_ibfk_3'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('yearID', 'teamshalf', ['yearID', 'lgID', 'teamID', 'Half'], unique=False)
    op.create_table('schools',
    sa.Column('schoolID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=False),
    sa.Column('name_full', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=55), nullable=True),
    sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=55), nullable=True),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=55), nullable=True),
    sa.PrimaryKeyConstraint('schoolID')
    )
    op.create_table('appearances',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('teamID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=False),
    sa.Column('team_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('G_all', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('GS', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_batting', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_defense', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_p', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_c', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_1b', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_2b', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_3b', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_ss', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_lf', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_cf', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_rf', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_of', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_dh', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_ph', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G_pr', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='appearances_ibfk_1'),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='appearances_ibfk_3'),
    sa.ForeignKeyConstraint(['team_ID'], ['teams.ID'], name='appearances_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('yearID', 'appearances', ['yearID', 'teamID', 'playerID'], unique=False)
    op.create_table('allstarfull',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('gameNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('gameID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=12), nullable=True),
    sa.Column('teamID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('team_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('GP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('startingPos', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='allstarfull_ibfk_1'),
    sa.ForeignKeyConstraint(['team_ID'], ['teams.ID'], name='allstarfull_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('playerID', 'allstarfull', ['playerID', 'yearID', 'gameNum', 'gameID', 'lgID'], unique=False)
    op.create_table('teamsfranchises',
    sa.Column('franchID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), nullable=False),
    sa.Column('franchName', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('active', mysql.CHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('NAassoc', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.PrimaryKeyConstraint('franchID')
    )
    op.create_table('fieldingof',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('stint', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('Glf', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('Gcf', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('Grf', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='fieldingof_ibfk_1'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('playerID', 'fieldingof', ['playerID', 'yearID', 'stint'], unique=False)
    op.create_table('battingarchives',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerId', mysql.VARCHAR(length=9), nullable=False),
    sa.Column('yearId', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('deletedAt', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('awardsmanagers',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('awardID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=75), nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=False),
    sa.Column('tie', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('notes', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='awardsmanagers_ibfk_1'),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='awardsmanagers_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('playerID', 'awardsmanagers', ['playerID', 'awardID', 'yearID', 'lgID'], unique=False)
    op.create_table('pitching',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('stint', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('teamID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('team_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('W', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('L', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('GS', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('CG', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SHO', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SV', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('IPouts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('H', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('ER', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('HR', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('BB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SO', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('BAOpp', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('ERA', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('IBB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('WP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('HBP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('BK', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('BFP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('GF', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('R', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SH', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SF', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('GIDP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='pitching_ibfk_1'),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='pitching_ibfk_3'),
    sa.ForeignKeyConstraint(['team_ID'], ['teams.ID'], name='pitching_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('playerID', 'pitching', ['playerID', 'yearID', 'stint'], unique=False)
    op.create_table('leagues',
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=False),
    sa.Column('league', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('active', mysql.CHAR(collation='utf8mb4_unicode_ci', length=1), nullable=False),
    sa.PrimaryKeyConstraint('lgID')
    )
    op.create_table('fielding',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('stint', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('teamID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('team_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('POS', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=False),
    sa.Column('G', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('GS', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('InnOuts', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('PO', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('A', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('E', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('DP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('PB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('WP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('CS', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('ZR', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='fielding_ibfk_1'),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='fielding_ibfk_3'),
    sa.ForeignKeyConstraint(['team_ID'], ['teams.ID'], name='fielding_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('playerID', 'fielding', ['playerID', 'yearID', 'stint', 'POS'], unique=False)
    op.create_table('halloffame',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('yearid', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('votedBy', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('ballots', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('needed', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('votes', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('inducted', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('needed_note', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=True),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='halloffame_ibfk_1'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('playerID', 'halloffame', ['playerID', 'yearid', 'votedBy'], unique=False)
    op.create_table('homegames',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('yearkey', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('leaguekey', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('teamkey', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('team_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('parkkey', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('park_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('spanfirst', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('spanlast', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('games', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('openings', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('attendance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('spanfirst_date', sa.DATE(), nullable=True),
    sa.Column('spanlast_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['leaguekey'], ['leagues.lgID'], name='homegames_ibfk_1'),
    sa.ForeignKeyConstraint(['park_ID'], ['parks.ID'], name='homegames_ibfk_3'),
    sa.ForeignKeyConstraint(['team_ID'], ['teams.ID'], name='homegames_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('analysis',
    sa.Column('analysis_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('G', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('AB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('R', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('H', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('2B', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('3B', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('HR', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('RBI', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('CS', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('BB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SO', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('IBB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('HBP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SH', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SF', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('GIDP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('OBP', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('TB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('RC', mysql.DECIMAL(precision=5, scale=1), nullable=True),
    sa.Column('RC27', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.CheckConstraint('"SF" >= 0', name='sf0'),
    sa.PrimaryKeyConstraint('analysis_ID')
    )
    op.create_index('analysisID', 'analysis', ['playerID', 'yearID'], unique=False)
    op.create_table('pitchingpost',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('round', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('teamID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('team_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('W', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('L', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('GS', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('CG', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SHO', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SV', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('IPouts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('H', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('ER', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('HR', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('BB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SO', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('BAOpp', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('ERA', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('IBB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('WP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('HBP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('BK', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('BFP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('GF', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('R', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SH', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SF', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('GIDP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='pitchingpost_ibfk_1'),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='pitchingpost_ibfk_3'),
    sa.ForeignKeyConstraint(['team_ID'], ['teams.ID'], name='pitchingpost_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('playerID', 'pitchingpost', ['playerID', 'yearID', 'round'], unique=False)
    op.create_table('battingpost',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('round', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('teamID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('team_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('G', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('AB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('R', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('H', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('2B', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('3B', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('HR', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('RBI', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('CS', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('BB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SO', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('IBB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('HBP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SH', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SF', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('GIDP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='battingpost_ibfk_1'),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='battingpost_ibfk_3'),
    sa.ForeignKeyConstraint(['team_ID'], ['teams.ID'], name='battingpost_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('yearID', 'battingpost', ['yearID', 'round', 'playerID'], unique=False)
    op.create_table('parks',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('parkalias', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('parkkey', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('parkname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('seriespost',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('round', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5), nullable=False),
    sa.Column('teamIDwinner', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('lgIDwinner', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('team_IDwinner', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('teamIDloser', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('team_IDloser', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lgIDloser', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('wins', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('losses', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('ties', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lgIDloser'], ['leagues.lgID'], name='seriespost_ibfk_2'),
    sa.ForeignKeyConstraint(['lgIDwinner'], ['leagues.lgID'], name='seriespost_ibfk_1'),
    sa.ForeignKeyConstraint(['team_IDloser'], ['teams.ID'], name='seriespost_ibfk_4'),
    sa.ForeignKeyConstraint(['team_IDwinner'], ['teams.ID'], name='seriespost_ibfk_3'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('yearID', 'seriespost', ['yearID', 'round'], unique=False)
    op.create_table('awardsshareplayers',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('awardID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('pointsWon', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('pointsMax', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('votesFirst', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='awardsshareplayers_ibfk_1'),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='awardsshareplayers_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('playerID', 'awardsshareplayers', ['playerID', 'awardID', 'yearID', 'lgID'], unique=False)
    op.create_table('salaries',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('teamID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=False),
    sa.Column('team_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('salary', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='salaries_ibfk_1'),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='salaries_ibfk_3'),
    sa.ForeignKeyConstraint(['team_ID'], ['teams.ID'], name='salaries_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('yearID', 'salaries', ['yearID', 'teamID', 'lgID', 'playerID'], unique=False)
    op.create_table('teams',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('teamID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=False),
    sa.Column('franchID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('divID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('div_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('teamRank', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('G', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('Ghome', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('W', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('L', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('DivWin', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('WCWin', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('LgWin', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('WSWin', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('R', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('AB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('H', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('2B', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('3B', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('HR', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('BB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SO', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('CS', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('HBP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SF', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('RA', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('ER', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('ERA', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('CG', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SHO', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SV', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('IPouts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('HA', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('HRA', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('BBA', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SOA', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('E', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('DP', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('FP', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('park', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('attendance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('BPF', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('PPF', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('teamIDBR', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('teamIDlahman45', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('teamIDretro', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.ForeignKeyConstraint(['div_ID'], ['divisions.ID'], name='teams_ibfk_2'),
    sa.ForeignKeyConstraint(['franchID'], ['teamsfranchises.franchID'], name='teams_ibfk_3'),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='teams_ibfk_1'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('yearID', 'teams', ['yearID', 'lgID', 'teamID'], unique=False)
    op.create_table('managers',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('teamID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=False),
    sa.Column('team_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('inseason', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('G', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('W', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('L', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('teamRank', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('plyrMgr', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='managers_ibfk_1'),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='managers_ibfk_3'),
    sa.ForeignKeyConstraint(['team_ID'], ['teams.ID'], name='managers_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('yearID', 'managers', ['yearID', 'teamID', 'inseason'], unique=False)
    op.create_table('fieldingofsplit',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('stint', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('teamID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('team_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('POS', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=False),
    sa.Column('G', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('GS', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('InnOuts', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('PO', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('A', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('E', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('DP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('PB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('WP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('CS', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('ZR', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='fieldingofsplit_ibfk_1'),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='fieldingofsplit_ibfk_3'),
    sa.ForeignKeyConstraint(['team_ID'], ['teams.ID'], name='fieldingofsplit_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('playerID', 'fieldingofsplit', ['playerID', 'yearID', 'stint', 'POS'], unique=False)
    op.create_table('awardssharemanagers',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('awardID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('pointsWon', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('pointsMax', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('votesFirst', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='awardssharemanagers_ibfk_1'),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='awardssharemanagers_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('playerID', 'awardssharemanagers', ['playerID', 'awardID', 'yearID', 'lgID'], unique=False)
    op.create_table('managershalf',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('teamID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=False),
    sa.Column('team_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('inseason', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('half', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('G', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('W', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('L', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('teamRank', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='managershalf_ibfk_1'),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='managershalf_ibfk_3'),
    sa.ForeignKeyConstraint(['team_ID'], ['teams.ID'], name='managershalf_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('playerID', 'managershalf', ['playerID', 'yearID', 'teamID', 'half'], unique=False)
    op.create_table('fieldingpost',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('teamID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('team_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('round', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=False),
    sa.Column('POS', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=False),
    sa.Column('G', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('GS', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('InnOuts', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('PO', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('A', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('E', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('DP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('TP', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('PB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('SB', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('CS', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='fieldingpost_ibfk_1'),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='fieldingpost_ibfk_3'),
    sa.ForeignKeyConstraint(['team_ID'], ['teams.ID'], name='fieldingpost_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('playerID', 'fieldingpost', ['playerID', 'yearID', 'round', 'POS'], unique=False)
    op.create_table('divisions',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('divID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=False),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=False),
    sa.Column('division', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('active', mysql.CHAR(collation='utf8mb4_unicode_ci', length=1), nullable=False),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='divisions_ibfk_1'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('divID', 'divisions', ['divID', 'lgID'], unique=False)
    op.create_table('collegeplaying',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('schoolID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='collegeplaying_ibfk_2'),
    sa.ForeignKeyConstraint(['schoolID'], ['schools.schoolID'], name='collegeplaying_ibfk_1'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('awardsplayers',
    sa.Column('ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('playerID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=False),
    sa.Column('awardID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('yearID', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=False),
    sa.Column('lgID', mysql.CHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('tie', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1), nullable=True),
    sa.Column('notes', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.ForeignKeyConstraint(['lgID'], ['leagues.lgID'], name='awardsplayers_ibfk_1'),
    sa.ForeignKeyConstraint(['playerID'], ['people.playerID'], name='awardsplayers_ibfk_2'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('playerID', 'awardsplayers', ['playerID', 'awardID', 'yearID', 'lgID'], unique=False)
    op.drop_table('AwardsPlayers')
    op.drop_table('user_people')
    # ### end Alembic commands ###
